### ISSUE TITLE
Made a POC

### ISSUE THREAD

**Issue by wyantb** [WhoopInc/frozen-moment#1]
https://gist.github.com/wyantb/996c53b00008194301c9

Implementing the idea sounded interesting, so I hacked up a prototype real quick.

Just patching `moment.fn` seemed the quickest route to success here.  Note that, obviously, I didn't expend a lot of effort trying to get the list of patched methods right.  Still, though I'd throw it out there. 

Also, I didn't implement the bit where you said that `.thaw` isn't available on non-frozen moments, and `.freeze` isn't available on frozen moments.  If I was using this patch, and developing some common API, I'd probably still tend towards calling `.freeze` on every incoming moment, and there's little sense in me calling `isFrozen` beforehand.

**Comment by butterflyhug** [comment]
Hey, that's pretty cool!  Thanks for sharing this, I hadn't really thought about whether this could be implemented by munging `moment.fn` in place.  I've been assuming that I'll want to make a shallow copy of `moment.fn` to serve as the prototype for frozen instances.  (And that may still be true, but now I have another option to consider.  :smiley: )

Interesting that you'd want to call `.freeze()` unconditionally -- it sounds like you're accepting moments as inputs from untrusted code?  I hadn't really thought about that particular use case much, but now that I have, I think I'm okay with supporting `freeze()` on already-frozen moments.  I'm still leaning against `.thaw()` on a mutable moment, though.

I might've been unclear in the README, but there is one other API difference in the way we're thinking about this.  I'm planning to return **cloned copies** from both `.freeze()` and `.thaw()`, instead of changing the behavior of the original instance.  If external code can switch the same object reference from immutable into mutable mode, I think you can still get the same sort of bugs that I've seen with mutable moments.

**Comment by wyantb** [comment]
https://gist.github.com/wyantb/ca17c1402cb848369735

I believe that's closer to what you intended, then, yes?  This implementation also has the advantage of less `moment.fn` manipulation - really, all I added were my two new methods, `freeze` and `isFrozen`.  `thaw`, as you suggested, is only available on frozen moments.  

Given the use of [`Object.create`](http://devdocs.io/javascript/global_objects/object/create), this is only available in >= IE9, so that might give some folks problems...could maybe manipulate `__proto__` as a fallback if that's available in earlier versions of IE; I honestly forget, not something I've had to support at work.

**Comment by butterflyhug** [comment]
Yep, exactly!  Obviously there's a bit of cleanup left, but this is quite close to the implementation I had in my head.  Would you mind contributing that file as a PR against this repo?  I'm planning to spend a couple hours hacking on this project later this afternoon, so your code would give me a great head start, and I'm happy to tie up a bunch of the obvious loose ends myself.

Thanks, @wyantb!

**Comment by wyantb** [comment]
Done.  Didn't bother with a project structure or anything, of course, just dumped into a file.
